// Code generated by "stringer -type=directionEnum"; DO NOT EDIT.

package part01

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DIRECTION_LEFT-0]
	_ = x[DIRECTION_RIGHT-1]
}

const _directionEnum_name = "DIRECTION_LEFTDIRECTION_RIGHT"

var _directionEnum_index = [...]uint8{0, 14, 29}

func (i directionEnum) String() string {
	if i < 0 || i >= directionEnum(len(_directionEnum_index)-1) {
		return "directionEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _directionEnum_name[_directionEnum_index[i]:_directionEnum_index[i+1]]
}
