// Code generated by "stringer -type=HandTypeEnum"; DO NOT EDIT.

package lib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HIGH_CARD-1]
	_ = x[ONE_PAIR-2]
	_ = x[TWO_PAIR-3]
	_ = x[THREE_OF_A_KIND-4]
	_ = x[FULL_HOUSE-5]
	_ = x[FOUR_OF_A_KIND-6]
	_ = x[FIVE_OF_A_KIND-7]
}

const _HandTypeEnum_name = "HIGH_CARDONE_PAIRTWO_PAIRTHREE_OF_A_KINDFULL_HOUSEFOUR_OF_A_KINDFIVE_OF_A_KIND"

var _HandTypeEnum_index = [...]uint8{0, 9, 17, 25, 40, 50, 64, 78}

func (i HandTypeEnum) String() string {
	i -= 1
	if i < 0 || i >= HandTypeEnum(len(_HandTypeEnum_index)-1) {
		return "HandTypeEnum(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _HandTypeEnum_name[_HandTypeEnum_index[i]:_HandTypeEnum_index[i+1]]
}
