// Code generated by "stringer -type=directionEnum"; DO NOT EDIT.

package part01

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DIRECTION_NORTH-1]
	_ = x[DIRECTION_EAST-2]
	_ = x[DIRECTION_SOUTH-3]
	_ = x[DIRECTION_WEST-4]
}

const _directionEnum_name = "DIRECTION_NORTHDIRECTION_EASTDIRECTION_SOUTHDIRECTION_WEST"

var _directionEnum_index = [...]uint8{0, 15, 29, 44, 58}

func (i directionEnum) String() string {
	i -= 1
	if i < 0 || i >= directionEnum(len(_directionEnum_index)-1) {
		return "directionEnum(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _directionEnum_name[_directionEnum_index[i]:_directionEnum_index[i+1]]
}
