// Code generated by "stringer -type=LayoutRuneEnum"; DO NOT EDIT.

package lib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EMPTY_RUNE-46]
	_ = x[FORWARD_SLASH_MIRROR-47]
	_ = x[BACK_SLASH_MIRROR-92]
	_ = x[VERTICAL_SPLITTER-124]
	_ = x[HORIZONTAL_SPLITTER-45]
	_ = x[priv_NON_ENERGIZED_RUNE-46]
	_ = x[priv_ENERGIZED_RUNE-35]
}

const (
	_LayoutRuneEnum_name_0 = "priv_ENERGIZED_RUNE"
	_LayoutRuneEnum_name_1 = "HORIZONTAL_SPLITTEREMPTY_RUNEFORWARD_SLASH_MIRROR"
	_LayoutRuneEnum_name_2 = "BACK_SLASH_MIRROR"
	_LayoutRuneEnum_name_3 = "VERTICAL_SPLITTER"
)

var (
	_LayoutRuneEnum_index_1 = [...]uint8{0, 19, 29, 49}
)

func (i LayoutRuneEnum) String() string {
	switch {
	case i == 35:
		return _LayoutRuneEnum_name_0
	case 45 <= i && i <= 47:
		i -= 45
		return _LayoutRuneEnum_name_1[_LayoutRuneEnum_index_1[i]:_LayoutRuneEnum_index_1[i+1]]
	case i == 92:
		return _LayoutRuneEnum_name_2
	case i == 124:
		return _LayoutRuneEnum_name_3
	default:
		return "LayoutRuneEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
